# Generated by Django 3.0.3 on 2020-06-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_educ'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='personal_profile',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
