# Generated by Django 3.0.3 on 2020-06-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_contactdetails_personal_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='workexp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=55)),
                ('employer', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('state', models.CharField(max_length=55)),
                ('startdate', models.DateField(max_length=55)),
                ('enddate', models.DateField(max_length=55)),
                ('jobdesc', models.CharField(max_length=2000)),
            ],
        ),
    ]
