# Generated by Django 3.0.3 on 2020-06-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_extrafield_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrafield',
            name='title',
        ),
    ]
