# Generated by Django 3.0.3 on 2020-06-20 11:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_extrafield_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafield',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
