# Generated by Django 3.0.3 on 2020-06-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200620_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrafield',
            name='explanation',
        ),
    ]
