# Generated by Django 3.0.3 on 2020-06-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_extrafield_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafield',
            name='explanation',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrafield',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
